import { createFileRoute } from "@tanstack/react-router";
import { Marketing, Meta, Action, pageHead } from "@/components/Marketing";
export const Route = createFileRoute("/how-it-works")({ head: () => pageHead("How FrontDesk Works | AI call handling, from call to next step", "How FrontDesk AI call handling is set up: we learn your business, configure answers and rules, and your existing number forwards calls when needed."), component: How });
const steps = [["We learn your business", "Tell us the questions you answer every day, and which calls always need a person."], ["We configure FrontDesk", "Agree approved information and the rules for capture, priority and escalation."], ["Your existing number forwards calls when needed", "Keep the number your customers know. Forwarding is arranged with you during setup."], ["FrontDesk answers", "The caller speaks naturally to FrontDesk instead of navigating a phone menu."], ["The enquiry is captured or flagged", "Details are recorded, and urgent or sensitive calls are flagged under your rules."], ["Your team receives the outcome", "A structured summary gives staff a clear next step."]];
const modes = [["Overflow", "FrontDesk picks up when your team is already on a call or can't get to the phone."], ["Out of hours", "Evenings, weekends and lunch breaks are covered, so enquiries aren't lost overnight."], ["Broader call handling", "For some businesses, FrontDesk answers more routine calls first — if that's how you configure it."]];
function How() {
  return <Marketing>
    <section className="border-b border-border"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">How it works</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-[1.08] sm:text-6xl">From ringing phone to clear next step.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">FrontDesk works alongside your team. You keep your existing number and decide when calls are forwarded.</p></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><ol className="grid gap-0 border-t border-border md:grid-cols-2">{steps.map(([t, d], i) => <li key={t} className="border-b border-border py-7 md:odd:pr-10 md:even:pl-10"><span className="text-sm font-bold text-brand">0{i + 1}</span><h2 className="mt-3 text-xl font-bold">{t}</h2><p className="mt-2 text-muted-foreground">{d}</p></li>)}</ol></section>
    <section className="border-y border-border bg-muted/40"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><Meta eyebrow="Your choice" title="Use it the way your business needs.">How much FrontDesk handles depends on how you configure it.</Meta><div className="mt-10 grid gap-7 md:grid-cols-3">{modes.map(([a, b]) => <div key={a} className="border-t-2 border-brand pt-5"><h3 className="text-xl font-bold">{a}</h3><p className="mt-3 text-muted-foreground">{b}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><Meta eyebrow="Boundaries" title="FrontDesk follows your rules.">It uses the information you approve and does not make decisions outside your configured rules. Uncertain or sensitive matters go back to your team.</Meta><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Action to="/demo">Request Demo Access</Action><Action to="/pricing" secondary>See planned pilot pricing</Action></div></section>
  </Marketing>;
}
