import { createFileRoute } from "@tanstack/react-router";
import { Marketing, Meta, Action, RequestSection, pageHead } from "@/components/Marketing";
export const Route = createFileRoute("/")({ head: () => pageHead("FrontDesk | AI reception support for UK dental practices", "Dental reception overflow and out-of-hours call handling for UK practices. FrontDesk captures routine enquiries and appointment requests for staff to follow up. 7-day pilot, £0 setup."), component: Home });

const summary = [["Caller", "New patient · Mr J. Patel"], ["Reason", "Cosmetic consultation enquiry"], ["Preferred time", "Tuesday afternoon"], ["Status", "Appointment request — not confirmed"], ["Next step", "Reception to call back"]];

function Home() {
  return <Marketing>
    <section className="border-b border-border"><div className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-16 sm:px-8 sm:py-20 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">AI reception support for UK dental practices</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-[1.07] sm:text-6xl">Never let a busy reception desk turn an unanswered call into a lost patient enquiry.</h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-muted-foreground">FrontDesk supports reception overflow and out-of-hours calls, answers routine questions using practice-approved information, and captures new-patient enquiries and appointment requests for your team to follow up.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Action to="/demo">Request Demo Access</Action><Action to="/how-it-works" secondary>See How It Works</Action></div><p className="mt-7 text-sm text-muted-foreground">Administrative support only — no clinical advice or confirmed bookings. Works alongside your existing team.</p></div>
      <div className="hidden justify-end lg:flex"><div className="w-full max-w-md border border-border bg-card p-6 shadow-xl shadow-primary/10"><div className="border-b border-border pb-4"><p className="text-xs font-bold uppercase tracking-[0.1em] text-brand">What your team receives</p><p className="mt-1 font-display font-bold">Call summary · FrontDesk Dental</p></div><dl className="mt-5 space-y-4 text-sm">{summary.map(([k, v]) => <div key={k} className="grid grid-cols-[110px_1fr] gap-3"><dt className="text-muted-foreground">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl><p className="mt-6 border-t border-border pt-4 text-xs text-muted-foreground">Fictional example — not a real patient record.</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-18 sm:px-8"><Meta eyebrow="Who it's for" title="Two focused products.">Built around the calls your team already handles.</Meta><div className="mt-10 grid gap-5 lg:grid-cols-[1.25fr_1fr]">
      <article className="flex flex-col justify-between border-2 border-primary bg-card p-7 sm:p-9"><div><div className="flex flex-wrap items-center gap-3"><p className="text-xs font-bold tracking-[0.14em] text-brand">FRONTDESK DENTAL</p><span className="bg-brand-soft px-2 py-1 text-xs font-bold text-brand">Pre-launch</span></div><h3 className="mt-8 max-w-md text-2xl font-bold sm:text-3xl">Reception overflow and out-of-hours support for dental practices.</h3><p className="mt-4 leading-relaxed text-muted-foreground">New-patient enquiries · Appointment requests · Routine questions · Callback requests. Administrative support only — no clinical advice.</p></div><div className="mt-9"><Action to="/dental">Explore FrontDesk Dental</Action></div></article>
      <article className="flex flex-col justify-between border border-border bg-card p-7 sm:p-9"><div><p className="text-xs font-bold tracking-[0.14em] text-brand">FRONTDESK TRADES</p><h3 className="mt-8 max-w-md text-2xl font-bold">Customers answered while you're on the job.</h3><p className="mt-4 leading-relaxed text-muted-foreground">Job details · Callback requests · Priority flags · Out-of-hours calls.</p></div><div className="mt-9"><Action to="/trades" secondary>Explore Trades</Action></div></article>
    </div></section>

    <section className="border-y border-border bg-muted/40"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><Meta eyebrow="When a call comes in" title="Answer. Capture. Pass it on." /><div className="mt-10 grid gap-9 md:grid-cols-3">{[["Answer", "FrontDesk picks up when your team is busy or closed, and answers routine questions using information you approve."], ["Capture", "It records who called, why, and what they'd like to happen next."], ["Pass it on", "Your team receives a structured summary. Urgent or sensitive calls are flagged under your rules."]].map(([a, b], i) => <div key={a}><span className="text-sm font-bold text-brand">0{i + 1}</span><h3 className="mt-4 text-2xl font-bold">{a}</h3><p className="mt-3 text-muted-foreground">{b}</p></div>)}</div><div className="mt-10"><Action to="/how-it-works" secondary>See the full process</Action></div></div></section>

    <section className="bg-brand-ink text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 md:grid-cols-2 md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.14em] opacity-75">Safe and in your control</p><h2 className="mt-4 text-3xl font-bold sm:text-4xl">FrontDesk follows your rules — not its own.</h2></div><ul className="space-y-3 text-sm leading-relaxed opacity-90">{["Uses only the information you approve.", "Escalation rules are set by your team.", "Anything uncertain or sensitive goes back to a person.", "Captures requests — it doesn't confirm bookings or give clinical advice."].map(x => <li key={x} className="border-b border-primary-foreground/15 pb-3">{x}</li>)}</ul></div></section>

    <div id="pilot"><RequestSection source="home" title="Join the FrontDesk early-access list." buttonText="Request Pilot Access" /></div>
  </Marketing>;
}
