import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ClipboardList, Phone, UserRoundCheck } from "lucide-react";
import { Marketing, Meta, Action, RequestSection, pageHead } from "@/components/Marketing";
export const Route = createFileRoute("/")({
  staticData: { sitemap: true }, head: () => pageHead("FrontDesk | AI reception support for UK dental practices", "Dental reception overflow and out-of-hours call handling for UK practices. FrontDesk captures routine enquiries and appointment requests for staff to follow up. 7-day pilot, £0 setup."), component: Home });

const summary = [["Reason", "New-patient enquiry"], ["Preferred callback", "Tuesday afternoon"], ["Next step", "Reception to call back"], ["Status", "Awaiting staff confirmation"]];
const steps = [{ icon: Phone, title: "Incoming enquiry", text: "Call your team can’t answer" }, { icon: ClipboardList, title: "Details captured", text: "Reason and callback time" }, { icon: UserRoundCheck, title: "Staff callback", text: "Your team follows up" }];

function Home() {
  return <Marketing>
    <section className="border-b border-border"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-10 sm:px-8 sm:py-14 lg:grid-cols-[1fr_1fr] lg:gap-14">
      <div><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">AI reception support for UK dental practices</p><h1 className="mt-4 text-4xl font-extrabold leading-[1.05] sm:text-5xl lg:text-[3.4rem]">Busy reception.<br />Keep the enquiry.</h1><p className="mt-5 max-w-xl text-lg leading-relaxed text-muted-foreground">FrontDesk AI is being developed to capture enquiries and callback details when your team can’t answer. Your staff confirm appointments and handle clinical questions.</p><div className="mt-7 flex flex-col gap-4 sm:flex-row sm:items-center"><Action to="/demo">Request Demo Access</Action><Link to="/how-it-works" className="inline-flex items-center gap-1 self-start rounded-sm text-sm font-semibold text-brand underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:self-auto">How it works <ArrowRight className="size-4" aria-hidden /></Link></div><p className="mt-6 text-sm font-semibold">7-day free pilot · Zero setup fee</p><p className="mt-1 text-sm text-muted-foreground">Pilot access follows call-flow agreement and testing.</p></div>
      <figure className="border border-border bg-card p-5 shadow-lg shadow-primary/5 sm:p-6" aria-label="Illustrative workflow">
        <figcaption className="text-xs font-bold uppercase tracking-[0.1em] text-brand">Illustrative workflow — live demo in preparation</figcaption>
        <ol className="mt-5 grid gap-3 sm:grid-cols-3 sm:gap-0">{steps.map(({ icon: Icon, title, text }, i) => <li key={title} className="relative flex items-center gap-3 sm:flex-col sm:items-center sm:text-center">{i > 0 && <span aria-hidden className="absolute right-1/2 top-6 hidden h-px w-full bg-border sm:block" />}<span className="relative z-10 flex size-12 shrink-0 items-center justify-center rounded-full border border-primary/30 bg-brand-soft text-brand"><Icon className="size-5" aria-hidden /></span><span className="sm:mt-3"><span className="block text-sm font-bold">{i + 1}. {title}</span><span className="block text-sm text-muted-foreground">{text}</span></span></li>)}</ol>
        <div className="mt-6 border border-border bg-background p-4"><p className="font-display text-sm font-bold">Sample callback request</p><dl className="mt-3 space-y-2 text-sm">{summary.map(([k, v]) => <div key={k} className="grid grid-cols-[140px_1fr] gap-2"><dt className="text-muted-foreground">{k}</dt><dd className="font-semibold">{v}</dd></div>)}</dl></div>
        <p className="mt-3 text-xs text-muted-foreground">Fictional example — not a real patient record.</p>
      </figure></div></section>

    <section className="mx-auto max-w-7xl px-5 py-18 sm:px-8"><Meta eyebrow="Who it's for" title="Two focused products.">Built around the calls your team already handles.</Meta><div className="mt-10 grid gap-5 lg:grid-cols-[1.25fr_1fr]">
      <article className="flex flex-col justify-between border-2 border-primary bg-card p-7 sm:p-9"><div><div className="flex flex-wrap items-center gap-3"><p className="text-xs font-bold tracking-[0.14em] text-brand">FRONTDESK DENTAL</p><span className="bg-brand-soft px-2 py-1 text-xs font-bold text-brand">Pre-launch</span></div><h3 className="mt-8 max-w-md text-2xl font-bold sm:text-3xl">Reception overflow and out-of-hours support for dental practices.</h3><p className="mt-4 leading-relaxed text-muted-foreground">New-patient enquiries · Appointment requests · Routine questions · Callback requests. Administrative support only — no clinical advice.</p></div><div className="mt-9"><Action to="/dental">Explore FrontDesk Dental</Action></div></article>
      <article className="flex flex-col justify-between border border-border bg-card p-7 sm:p-9"><div><p className="text-xs font-bold tracking-[0.14em] text-brand">FRONTDESK TRADES</p><h3 className="mt-8 max-w-md text-2xl font-bold">Customers answered while you're on the job.</h3><p className="mt-4 leading-relaxed text-muted-foreground">Job details · Callback requests · Priority flags · Out-of-hours calls.</p></div><div className="mt-9"><Action to="/trades" secondary>Explore Trades</Action></div></article>
    </div></section>

    <section className="border-y border-border bg-muted/40"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><Meta eyebrow="When a call comes in" title="Answer. Capture. Pass it on." /><div className="mt-10 grid gap-9 md:grid-cols-3">{[["Answer", "FrontDesk picks up when your team is busy or closed, and answers routine questions using information you approve."], ["Capture", "It records who called, why, and what they'd like to happen next."], ["Pass it on", "Your team receives a structured summary. Urgent or sensitive calls are flagged under your rules."]].map(([a, b], i) => <div key={a}><span className="text-sm font-bold text-brand">0{i + 1}</span><h3 className="mt-4 text-2xl font-bold">{a}</h3><p className="mt-3 text-muted-foreground">{b}</p></div>)}</div><div className="mt-10"><Action to="/how-it-works" secondary>See the full process</Action></div></div></section>

    <section className="bg-brand-ink text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 md:grid-cols-2 md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.14em] opacity-75">Safe and in your control</p><h2 className="mt-4 text-3xl font-bold sm:text-4xl">FrontDesk follows your rules — not its own.</h2></div><ul className="space-y-3 text-sm leading-relaxed opacity-90">{["Uses only the information you approve.", "Escalation rules are set by your team.", "Anything uncertain or sensitive goes back to a person.", "Captures requests — it doesn't confirm bookings or give clinical advice."].map(x => <li key={x} className="border-b border-primary-foreground/15 pb-3">{x}</li>)}</ul></div></section>

    <div id="pilot"><RequestSection source="home" title="Join the FrontDesk early-access list." buttonText="Request Pilot Access" /></div>
  </Marketing>;
}
