import { createFileRoute } from "@tanstack/react-router";
import { useRef, useState, type KeyboardEvent } from "react";
import { ArrowRight, ClipboardList, Phone, Stethoscope, UserRoundCheck, Wrench, MessagesSquare, FlaskConical, ChevronDown, Check } from "lucide-react";
import { Marketing, Action, RequestSection, pageHead } from "@/components/Marketing";
import { Button } from "@/components/ui/button";
import ribbon from "@/assets/callwoven-ribbon.png";

export const Route = createFileRoute("/")({
 staticData: { sitemap: true },
 head: () => pageHead("Callwoven | AI reception for dental practices and service trades", "AI reception support for dental practices and service businesses. Discuss a 7-day free pilot with zero setup fee; your team stays in control."),
 component: Home,
});
const examples = {
 dental: [["Caller", "Alex Morgan"], ["Enquiry", "New-patient appointment request"], ["Requested callback", "Tuesday afternoon"], ["Next step", "Reception to call back"]],
 trades: [["Caller", "Jamie Taylor"], ["Enquiry", "Boiler service request"], ["Requested callback", "Tomorrow morning"], ["Next step", "Team to call back"]],
} as const;
type Sector = keyof typeof examples;
const tabs: {id: Sector; label: string}[] = [{id:"dental",label:"Dental"},{id:"trades",label:"Trades"}];
function EnquiryCard({ compact = false }: { compact?: boolean }) {
 const [sector, setSector] = useState<Sector>("dental");
 const refs = useRef<(HTMLButtonElement | null)[]>([]);
 const key = (e: KeyboardEvent, i: number) => {
  const n = e.key === "ArrowRight" ? (i + 1) % 2 : e.key === "ArrowLeft" ? (i + 1) % 2 : e.key === "Home" ? 0 : e.key === "End" ? 1 : -1;
  const next = tabs[n]; if (!next) return; e.preventDefault(); setSector(next.id); refs.current[n]?.focus();
 };
 const prefix = compact ? "hero" : "received";
 return <figure className={`relative rounded-lg border border-border bg-card woven-shadow ${compact ? "w-full max-w-[350px] p-5 sm:p-6" : "w-full max-w-lg p-6 sm:p-8"}`}>
 <figcaption className="text-xs text-muted-foreground">{compact ? "Illustrative example" : "Illustrative example — fictional details"}</figcaption>
 <div className="mt-4 flex items-center gap-3 border-b border-border pb-5"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-secondary"><ClipboardList className="size-5" aria-hidden /></span><p className="text-base font-semibold">Callback requested</p></div>
 <div role="tablist" aria-label="Example business type" className="mt-4 flex gap-2">{tabs.map((t,i) => <Button key={t.id} ref={el => {refs.current[i] = el;}} id={`${prefix}-${t.id}`} role="tab" type="button" variant={sector === t.id ? "secondary" : "ghost"} size="sm" aria-selected={sector === t.id} aria-controls={`${prefix}-summary`} tabIndex={sector === t.id ? 0 : -1} onKeyDown={e => key(e,i)} onClick={() => setSector(t.id)}>{t.label}</Button>)}</div>
 <div id={`${prefix}-summary`} role="tabpanel" aria-labelledby={`${prefix}-${sector}`}><dl className="mt-4 space-y-4 text-[13px]">{examples[sector].map(([k,v]) => <div key={k} className="grid grid-cols-[105px_1fr] gap-3"><dt className="text-muted-foreground">{k}</dt><dd className="font-medium leading-relaxed">{v}</dd></div>)}</dl><p className="mt-5 flex items-center gap-2 border-t border-border pt-4 text-xs text-copper-ink"><UserRoundCheck className="size-4 shrink-0" aria-hidden />{sector === "dental" ? "Appointment not confirmed" : "Visit not confirmed"}</p></div>
 {!compact && <p className="mt-4 text-xs leading-relaxed text-muted-foreground">Fictional example — not a real customer or patient record.</p>}
 </figure>;
}
const sectors = [
 {icon:Stethoscope, title:"Dental practices",copy:"Keep administrative enquiries moving while reception is busy.", examples:"New-patient enquiries · Appointment requests · Callback details", note:"Your staff confirm appointments and handle clinical questions.", to:"/dental" as const},
 {icon:Wrench,title:"Trades & service businesses",copy:"Capture enquiries while your team is on the job.",examples:"Plumbing · Heating / HVAC · Electrical",note:"Your team confirms availability, quotes and next steps.",to:"/trades" as const},
];
const questions = [
 ["Who is Callwoven for?", "Dental practices and service businesses, including plumbing, heating/HVAC and electrical teams, that want to discuss administrative enquiry and callback capture."],
 ["What details could it capture?", "The agreed call flow can be configured around caller name, contact number, location, reason for calling and a requested callback time. We agree the fields and test them before the pilot."],
 ["Does it confirm appointments or visits?", "No. Your staff confirm appointments, availability, quotes and next steps. A request is not a confirmed booking."],
 ["Does it give clinical advice?", "No. Clinical questions, uncertain matters and sensitive enquiries are passed back to your team under your agreed rules."],
 ["What happens before a pilot starts?", "We agree the scope, call-handling requirements, data handling and service terms, then test the call flow. Live demos are in preparation; no public live demo is available yet."],
];
function Home() {return <Marketing>
 <section className="relative"><div className="mx-auto grid max-w-7xl items-center gap-7 px-5 pb-9 pt-12 sm:px-8 sm:pt-14 lg:grid-cols-[1.05fr_1fr] lg:gap-7 lg:pb-10 lg:pt-14">
 <div className="relative z-10 min-w-0"><p className="text-[11px] font-medium uppercase text-muted-foreground">AI reception. Human follow-through.</p><h1 className="mt-5 max-w-xl text-[48px] leading-[1.04] sm:text-[64px] lg:text-[76px]">A clear next step<br className="hidden sm:block"/> for every call<span className="text-copper">.</span></h1><p className="mt-6 max-w-[470px] text-base leading-relaxed text-muted-foreground sm:text-lg">AI reception support for dental practices and service businesses. Capture administrative enquiries and callback requests when your team is busy.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Action to="/" hash="pilot">Discuss a free pilot</Action><Action to="/how-it-works" secondary>See how it works</Action></div><p className="mt-5 text-xs font-medium text-muted-foreground">7-day free pilot · Zero setup fee</p><p className="mt-1 text-xs text-muted-foreground">Pilot access follows call-flow agreement and testing.</p></div>
 <div className="relative flex min-h-[410px] min-w-0 items-center justify-center sm:min-h-[430px] lg:justify-end"><img src={ribbon} width={1536} height={1024} alt="" className="woven-ribbon pointer-events-none absolute left-1/2 top-1/2 w-[125%] max-w-none -translate-x-1/2 -translate-y-1/2" /><div className="relative z-10 w-full max-w-[350px] lg:mr-3"><EnquiryCard compact /></div></div>
 </div><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 pb-8 text-xs text-muted-foreground sm:px-8"><p>Built around your team. Not a replacement for it.</p><p>Dental practices & service trades</p></div></section>
 <section id="sectors" className="mx-auto grid max-w-7xl gap-5 px-5 pb-16 sm:px-8 md:grid-cols-2">{sectors.map(({icon:Icon,title,copy,examples,note,to},i) => <article key={to} className={`group flex flex-col rounded-lg border p-6 sm:p-7 ${i === 0 ? "border-border bg-secondary/60" : "border-copper/25 bg-accent/50"}`}><div className="flex items-center gap-4"><span className={`flex size-14 shrink-0 items-center justify-center rounded-full ${i === 0 ? "bg-secondary" : "bg-accent text-copper-ink"}`}><Icon className="size-7" strokeWidth={1.4} aria-hidden /></span><h2 className="text-[30px] leading-tight">{title}</h2><Button asChild variant="outline" size="icon" className="ml-auto size-10 shrink-0 rounded-full bg-transparent" title={`Explore ${title}`}><a href={to} aria-label={`Explore ${title}`}><ArrowRight /></a></Button></div><p className="mt-5 text-base font-medium">{copy}</p><p className="mt-3 text-xs leading-relaxed text-muted-foreground">{examples}</p>{i === 1 && <p className="mt-2 text-xs leading-relaxed text-muted-foreground">Caller name, contact number, location and reason for calling.</p>}<p className="mt-auto border-t border-foreground/10 pt-4 text-xs leading-relaxed text-muted-foreground">{note}</p></article>)}</section>
 <section className="border-y border-border bg-secondary/35"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-medium uppercase text-muted-foreground">The proposed pilot process</p><h2 className="mt-4 text-4xl sm:text-5xl">Good conversations.<br/>Clear handovers.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">Start with your requirements, test the details, then review what your team needs to follow up.</p></div><ol className="mt-12 grid gap-8 md:grid-cols-3">{[{icon:MessagesSquare,title:"Agree your requirements",copy:"Decide which enquiries to capture and which calls need a person."},{icon:FlaskConical,title:"Test the call flow",copy:"Review the wording, capture fields and intended summary destination before the pilot."},{icon:UserRoundCheck,title:"Review. Then follow up.",copy:"Your team reviews captured enquiries and decides the next step."}].map(({icon:Icon,title,copy},i) => <li key={title} className="border-t border-border pt-6"><div className="flex items-center justify-between"><Icon className="size-7" strokeWidth={1.4} aria-hidden/><span className="font-display text-2xl text-copper-ink">0{i+1}</span></div><h3 className="mt-5 text-2xl">{title}</h3><p className="mt-3 max-w-xs text-sm leading-relaxed text-muted-foreground">{copy}</p></li>)}</ol></div></section>
 <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:px-8 lg:grid-cols-2"><div><p className="text-xs font-medium uppercase text-muted-foreground">Incoming enquiry → Details captured → Your team follows up</p><h2 className="mt-5 text-4xl sm:text-5xl">Less searching.<br/>A useful next step.</h2><p className="mt-5 max-w-md text-base leading-relaxed text-muted-foreground">A concise callback summary, shaped around the information your team needs. Your people stay in control.</p><ul className="mt-7 space-y-4 text-sm">{["Caller details and reason for calling", "Requested callback time", "Appointments and visits confirmed by your staff"].map(t => <li key={t} className="flex items-center gap-3"><Check className="size-4 text-copper-ink" aria-hidden />{t}</li>)}</ul><p className="mt-7 text-xs text-muted-foreground">Illustrative workflow. Live demos are in preparation.</p></div><div className="flex justify-center lg:justify-end"><EnquiryCard /></div></section>
 <div id="pilot"><RequestSection source="home" title="See whether Callwoven fits your business." intro="Discuss a 7-day free pilot with zero setup fee. We’ll agree the scope and test the call flow before it starts." buttonText="Discuss a free pilot" /></div>
 <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-xs font-medium uppercase text-muted-foreground">A few things worth knowing</p><h2 className="mt-4 text-4xl sm:text-5xl">Clear from<br/>the start.</h2><a href="mailto:satya@callwoven.com" className="mt-5 inline-block text-sm underline underline-offset-4">Ask us a question <ArrowRight className="ml-2 inline size-4" /></a></div><div>{questions.map(([q,a]) => <details key={q} className="group border-b border-border"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 py-5 text-base font-medium">{q}<ChevronDown className="size-4 shrink-0 transition-transform group-open:rotate-180" aria-hidden /></summary><p className="pb-5 text-sm leading-relaxed text-muted-foreground">{a}</p></details>)}</div></section>
 </Marketing>;}
