import { createFileRoute } from "@tanstack/react-router";
import { Marketing, Meta, Action, pageHead } from "@/components/Marketing";
export const Route = createFileRoute("/pricing")({
  staticData: { sitemap: true }, head: () => pageHead("Callwoven Pricing | 7-day pilot", "Discuss a tailored Callwoven pilot for your business. Indicative plans start at £149/month after the 7-day pilot; no payment is taken through this website."), component: Pricing });
const factors = [["Call volume", "How many calls you'd like Callwoven to handle."], ["Workflow complexity", "The questions, capture fields and escalation rules you need."], ["Locations and numbers", "How many sites or phone numbers are covered."], ["Configuration", "Any specific setup your team requires."]];
const included = ["Setup based on your business information", "Answering routine enquiries with approved information", "Capture of caller details and enquiry reason", "Flags for urgent or sensitive calls under your rules", "Structured summaries for your team", "Your existing number kept — calls forwarded when needed"];
function Pricing() {
  return <Marketing>
    <section className="border-b border-border"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand">Pricing</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-[1.08] sm:text-6xl">Try it first. Then choose what fits.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Talk to us about a pilot tailored to your business. Requesting a pilot is free, and no payment is taken through this website.</p></div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-5 py-16 sm:px-8 lg:grid-cols-2">
      <article className="flex flex-col border-2 border-primary bg-card p-7 sm:p-9"><p className="text-xs font-bold tracking-[0.14em] text-brand">7-DAY PILOT</p><h2 className="mt-4 text-3xl font-bold">7-day pilot</h2><p className="mt-5 text-5xl font-extrabold">£0<span className="text-base font-medium text-muted-foreground"> setup</span></p><p className="mt-4 text-muted-foreground">Once onboarding, safeguards and service terms are agreed, you can try the configured service for 7 days. No commitment to continue.</p><ul className="my-8 flex-1 space-y-3 border-t border-border pt-6">{included.map(f => <li key={f} className="flex gap-2 text-sm leading-relaxed"><span className="font-bold text-brand" aria-hidden="true">✓</span>{f}</li>)}</ul><Action to="/" hash="pilot">Request Pilot Access</Action></article>
      <article className="flex flex-col border border-border bg-card p-7 sm:p-9"><p className="text-xs font-bold tracking-[0.14em] text-brand">AFTER THE PILOT</p><h2 className="mt-4 text-3xl font-bold">Plans from</h2><p className="mt-5 text-5xl font-extrabold">£149<span className="text-base font-medium text-muted-foreground"> / month</span></p><p className="mt-4 text-muted-foreground">After the pilot, choose the setup that fits your call volume and workflow. Pricing is agreed before you go live.</p><h3 className="mt-8 border-t border-border pt-6 text-sm font-bold uppercase tracking-[0.1em]">What affects pricing</h3><dl className="mt-4 flex-1 space-y-4">{factors.map(([k, v]) => <div key={k}><dt className="font-semibold">{k}</dt><dd className="text-sm text-muted-foreground">{v}</dd></div>)}</dl><div className="mt-8"><Action to="/demo" secondary>Request a Demo</Action></div></article>
    </section>
    <section className="border-t border-border bg-muted/40 py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Meta eyebrow="No surprises" title="We'll agree the details with you.">We’ll discuss the scope and test the call flow before a pilot. Rather than guess usage limits, we set pricing once we understand your calls. You'll know the monthly price before anything goes live.</Meta></div></section>
  </Marketing>;
}
